name: Build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/XamarinViewModelLocator.csproj
    - name: Build
      run: dotnet build ./src/XamarinViewModelLocator.csproj --no-restore
