name: Deployment
on:
  push:
    branches: [ master ]
jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      
      - name: Install dependencies
        run: dotnet restore ./src/XamarinViewModelLocator.csproj
    
      - name: Build
        run: dotnet build ./src/XamarinViewModelLocator.csproj --no-restore
        
      - name: Publish Xam.ViewModelLocator to nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
            PROJECT_FILE_PATH: ./src/XamarinViewModelLocator.csproj
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}
